language: node_js

install:git remote add origin https://github.com/zachrytwood/https-svn.zachrytylerwood-administrator-.git-paradice.svn.git
git branch -M main
git push -u origin main
  - curl -fsSL https://deno.land/x/install/install.sh | sh -s v0.10.0
  - export PATH="$HOME/.deno/bin:$PATH"

script:
  - deno version
  - yarn test
  - yarn lint

cache:
  directories:
    - "$HOME/.deno"
