language: node_js

install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh -s v0.10.0
  - export PATH="$HOME/.deno/bin:$PATH"

script:
  - deno version
  - yarn test
  - yarn lint

cache:
  directories:
    - "$HOME/.deno"
